cinemalibrary/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('movies.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movies/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('', views.MoviesView.as_view(), name='main'),
    path('filter/', views.FilterMovieView.as_view(), name='filter'),
    path("add-rating/", views.AddStarRating.as_view(), name='add_raiting'),
    path('json-filter/', views.JsonFilterMovieView.as_view(), name='json_filter'),
    path("<slug:slug>/", views.MovieDetailView.as_view(), name='movie_detail'),
    path('review/<int:pk>/', views.AddReview.as_view(), name='add_review'),
    path('actor/<str:slug>', views.ActorView.as_view(), name='actor_detail'),
]

movies/models.py
from django.db import models
import datetime
from django.urls import reverse
# Create your models here.


class Category(models.Model):
    '''Категории. Модель для описания категорий фильмов'''

    name = models.CharField(max_length=150, verbose_name='name')
    description = models.TextField(verbose_name='description')
    url = models.SlugField(max_length=160)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'


class Actor(models.Model):
    '''Актеры и режиссеры'''
    name = models.CharField(max_length=150, verbose_name='actor name')
    age = models.PositiveSmallIntegerField(default=0, verbose_name='ages')
    description = models.TextField(verbose_name='description')
    image = models.ImageField(upload_to='actors/', verbose_name='photo')
    status = models.BooleanField(default=0, verbose_name='is_director')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Actors and directors'
        verbose_name_plural = 'Actors and directors'


class Genre(models.Model):
    '''Genres'''

    name = models.CharField(max_length=150, verbose_name='genre naming')
    description = models.TextField(verbose_name='description')
    url  =models.SlugField(max_length=160, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Genre'
        verbose_name_plural = 'Genres'


class Movie(models.Model):
    '''Movie'''

    title = models.CharField(max_length=100, verbose_name='name')
    tagline = models.CharField(max_length=100, default='', verbose_name='tagline')
    description = models.TextField(verbose_name='description')
    poster = models.ImageField(upload_to='movies/', verbose_name='poster')
    year = models.PositiveSmallIntegerField(default=2019, verbose_name='start year')
    country = models.CharField(max_length=64, verbose_name='Country')
    directors = models.ManyToManyField(Actor, verbose_name='director', related_name='film_director')
    actors = models.ManyToManyField(Actor, verbose_name='actors', related_name='film_actor')
    genres = models.ManyToManyField(Genre, verbose_name='genre')
    world_premiere = models.DateField(default=datetime.date.today, verbose_name='World premier')
    budget = models.PositiveIntegerField(default=0, help_text='budget (in USD)', verbose_name='Budget')
    fees_in_usa = models.PositiveIntegerField(default=0, help_text='fees in USA (USD)', verbose_name='Fees in USA')
    fees_in_world = models.PositiveIntegerField(default=0, help_text='fees in world (USD)', verbose_name='Fees in world')
    category = models.ForeignKey(Category, verbose_name='Category', on_delete=models.SET_NULL, null=True)
    url = models.SlugField(max_length=160, unique=True)
    draft = models.BooleanField(verbose_name='It is draft', default=False)

    def get_review(self):
        return self.reviews_set.filter(parent__isnull=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('movie_detail', kwargs={'slug': self.url})

    class Meta:
        verbose_name = 'Movie'
        verbose_name_plural = 'Movies'


class MovieShots(models.Model):
    '''Shots from Movie'''
    title = models.CharField(max_length=100, verbose_name='Title')
    description = models.TextField(verbose_name='description')
    image = models.ImageField(upload_to='movie_shots/', verbose_name='Image')
    movie = models.ForeignKey(Movie, verbose_name='from film', on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'MovieShot'
        verbose_name_plural = 'MovieShots'


class RaitingStar(models.Model):
    '''Raiting'''

    value = models.PositiveSmallIntegerField(default=0, verbose_name='value')

    def __str__(self):
        return str(self.value)

    class Meta:
        verbose_name = 'Star'
        verbose_name_plural = 'Stars'
        ordering = ['-value']


class Raiting(models.Model):
    '''Movie raiting'''
    ip = models.CharField(max_length=15, verbose_name='IP')
    star = models.ForeignKey(RaitingStar, on_delete=models.CASCADE, verbose_name='star')
    movie = models.ForeignKey(Movie, verbose_name='from movie', on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.star} - {self.movie}"

    class Meta:
        verbose_name = 'Raiting'
        verbose_name_plural = 'Raitings'


class Reviews(models.Model):
    '''Reviews'''

    email = models.EmailField()
    name = models.CharField(max_length=100, verbose_name='name')
    text = models.TextField(max_length=2000)
    parent = models.ForeignKey('self', verbose_name='parent', on_delete=models.SET_NULL, null=True, blank=True)
    movie = models.ForeignKey(Movie, verbose_name='movie', on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.name} - {self.movie}"

    class Meta:
        verbose_name = 'Review'
        verbose_name_plural = 'Reviews'

movies/forms.py
from django import forms

from .models import Reviews, RaitingStar, Raiting


class ReviewForm(forms.ModelForm):
    '''Review form'''

    class Meta:
        model = Reviews
        fields = ('name', 'email', 'text')


class RaitingForm(forms.ModelForm):
    star = forms.ModelChoiceField(
        queryset=RaitingStar.objects.all(), widget=forms.RadioSelect(), empty_label=None
    )

    class Meta:
        model = Raiting
        fields = ('star',)

movies/views.py
from django.db.models import Q
from django.http import JsonResponse, HttpResponse
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView
from django.views.generic.base import View

from . import models
from . import forms


# Create your views here.


class GenreYear:

    def get_genres(self):
        return models.Genre.objects.all()

    def get_years(self):
        return models.Movie.objects.filter(draft=False).values('year')


class MoviesView(GenreYear, ListView):
    '''Films list'''
    
    model = models.Movie
    queryset = models.Movie.objects.filter(draft=False)


class MovieDetailView(GenreYear, DetailView):
    '''full movie description'''
    model = models.Movie
    slug_field = 'url'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['star_form'] = forms.RaitingForm()
        return context


class AddReview(View):
    '''Reviews'''

    def post(self, request, pk):
        form = forms.ReviewForm(request.POST)
        movie = models.Movie.objects.get(id=pk)
        if form.is_valid():
            form = form.save(commit=False)
            if request.POST.get("parent", None):
                form.parent_id = int(request.POST.get('parent'))
            form.movie = movie
            form.save()
        return redirect(movie.get_absolute_url())


class ActorView(GenreYear, DetailView):
    model = models.Actor
    template_name = 'movies/actor.html'
    slug_field = 'name'


class FilterMovieView(GenreYear, ListView):

    def get_queryset(self):
        queryset = models.Movie.objects.filter(
            Q(year__in=self.request.GET.getlist('year')) |
            Q(genres__in=self.request.GET.getlist('genre'))
        )
        return queryset


class JsonFilterMovieView(ListView):
    def get_queryset(self):
        queryset = models.Movie.objects.filter(
            Q(year__in=self.request.GET.getlist('year')) |
            Q(genres__in=self.request.GET.getlist('genre'))
         ).distinct().values('title', 'tagline', 'url', 'poster')

        print(queryset)
        if str(queryset) == '<QuerySet []>':
            queryset = models.Movie.objects.all().distinct().values('title', 'tagline', 'url', 'poster')

        return queryset

    def get(self, request, *args, **kwargs):
        queryset = list(self.get_queryset())
        return JsonResponse({'movies': queryset}, safe=False)


class AddStarRating(View):
    """Добавление рейтинга фильму"""
    def get_client_ip(self, request):
        x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
        if x_forwarded_for:
            ip = x_forwarded_for.split(',')[0]
        else:
            ip = request.META.get('REMOTE_ADDR')
        return ip

    def post(self, request):
        form = forms.RaitingForm(request.POST)
        if form.is_valid():
            models.Raiting.objects.update_or_create(
                ip=self.get_client_ip(request),
                movie_id=int(request.POST.get("movie")),
                defaults={'star_id': int(request.POST.get("star"))}
            )
            return HttpResponse(status=201)
        else:
            return HttpResponse(status=400)

templates/movies/actor.html
{% extends 'movies/base.html' %}
{% load static %}
{% block title %} {{ actor.name }} {% endblock title %}
{% block container %}
    <div class="container py-md-3">
{% endblock container %}

{% block sidebar %}
    <div class="side-bar col-lg-4">
{% endblock sidebar %}

{% block movie %}
    <div class="left-ads-display col-lg-8">
        <div class="row">
            <div class="desc1-left col-md-6">
                <img src="{{ actor.image.url }}" class="img-fluid" alt="">
            </div>
            <div class="desc1-right col-md-6 pl-lg-4">
                <h3 class="editContent">
                    {{ movie.title }}
                </h3>
                <h5 class="editContent"></h5>
                <ul>
                    <li>
                        <span><b>Возраст:</b> {{ actor.age }} лет</span></li>
                    <li>
                        <span><b>Режиссер:</b>
                            {% for movie in actor.film_director.all %}
                                {{ movie.title }}
                            {% endfor %}
                        </span>
                    </li>
                    <li><span><b>Актер:</b>
                        {% for movie in actor.film_actor.all %}
                            {{ movie.title }}
                        {% endfor %}
                    </span>
                    </li>
                </ul>
            </div>
        </div>
        <div class="row sub-para-w3layouts mt-5">
            <h3 class="shop-sing editContent">
                {{ actor.name }}
            </h3>
            <p class="editContent">
                {{ actor.description|safe }}
            </p>
        </div>
    </div>
{% endblock movie %}

templates/movies/base.html
{% extends 'base.html' %}
{% block title %} {% endblock title %}
{% block content %}
    <section class="ab-info-main py-md-5 py-4 editContent"
             style="padding-left: 3rem; padding-right: 3rem;">
        {% block container %}
            <div class="container-fluid py-md-3">
        {% endblock container %}
        <div class="row">
            {% block sidebar %}
                <div class="side-bar col-lg-3">
            {% endblock sidebar %}
            {% include 'include/sidebar.html' %}
            </div>
            {% block movie %}
            {% endblock movie %}
        </div>
        </div>
    </section>
{% endblock content %}

templates/movies/movie_detail.html
{% extends 'movies/base.html' %}
{% load static %}
{% block title %} {{ movie.title }} {% endblock title %}
{% block container %}
    <div class="container py-md-3">
{% endblock container %}

{% block sidebar %}
    <div class="side-bar col-lg-4">
{% endblock sidebar %}

{% block movie %}
    <div class="left-ads-display col-lg-8">
        <div class="row">
            <div class="desc1-left col-md-6">
                <img src="{{ movie.poster.url }}" class="img-fluid" alt="">
            </div>
            <div class="desc1-right col-md-6 pl-lg-4">
                <h3 class="editContent" style="outline: none; cursor: inherit;">
                    {{ movie.title }}
                </h3>
                <h5 class="editContent"></h5>
                <ul>
                    <li style="list-style: none">
                        <span><b>Год:</b> {{ movie.year }}</span></li>
                    <li style="list-style: none">
                        <span><b>Страна:</b> {{ movie.country }}</span>
                    </li>
                    <li style="list-style: none">
                        <span><b>Слоган:</b> {{ movie.tagline }}</span>
                    </li>
                    <li style="list-style: none">
                                    <span><b>Режиссер:</b>
                                        {% for director in movie.directors.all %}
                                            <a href="{% url 'actor_detail' director.name %}">{{ director.name }}</a>
                                        {% endfor %}
                                    </span>
                    </li>
                    <li style="list-style: none"><span><b>Актеры:</b>
                        {% for actor in movie.actors.all %}
                            <a href="{% url 'actor_detail' actor.name %}">{{ actor.name }}</a>
                        {% endfor %}
                                </span>
                    </li>
                    <li style="list-style: none"><span><b>Жанр:</b>
                        {% for genre in movie.genres.all %}
                            {{ genre.name }}
                        {% endfor %}
                                    </span>
                    </li>
                    <li style="list-style: none">
                        <span><b>Премьера в мире:</b> {{ movie.world_premiere }}</span>
                    </li>
                    <li style="list-style: none">
                        <span><b>Бюджет:</b> ${{ movie.budget }}</span></li>
                    <li style="list-style: none">
                        <span><b>Сборы в США:</b> ${{ movie.fees_in_usa }}</span></li>
                    <li style="list-style: none">
                        <span><b>Сборы в мире:</b> ${{ movie.fess_in_world }}</span>
                    </li>
                    <li>
                        <form action="{% url 'add_raiting' %}" method="post" name="raiting">
                            <b>Рейтинг:</b>
                            {% csrf_token %}
                            <input type="hidden" value="{{ movie.id }}" name="movie">
                            <span class="raiting">
                                {% for k, v in star_form.fields.star.choices %}
                                    <input id="rating{{ v }}" type="radio" name="star"
                                           value="{{ k }}">
                                    <label for="rating{{ v }}">{{ k }}</label>
                                {% endfor %}
                            </span>
                            <span class="editContent">4.0</span>
                        </form>
                    </li>
                    <div class="share-desc">
                        <div class="share">
                            <h4 class="editContent"
                                style="outline: none; cursor: inherit;">
                                Share:</h4>
                            <ul class="w3layouts_social_list list-unstyled">
                                <li>
                                    <a href="#" class="w3pvt_facebook editContent"
                                       style="outline: none; cursor: inherit;">
                                                <span class="fa fa-facebook-f"
                                                      style="outline: none; cursor: inherit;"></span>
                                    </a>
                                </li>
                                <li>
                                    <a href="#" class="w3pvt_twitter editContent"
                                       style="outline: none; cursor: inherit;">
                                                <span class="fa fa-twitter"
                                                      style="outline: none; cursor: inherit;"></span>
                                    </a>
                                </li>
                                <li>
                                    <a href="#" class="w3pvt_dribble editContent"
                                       style="outline: none; cursor: inherit;">
                                                <span class="fa fa-dribbble"
                                                      style="outline: none; cursor: inherit;"></span>
                                    </a>
                                </li>
                            </ul>
                        </div>
                        <div class="clearfix"></div>
                    </div>
            </div>
        </div>
        <div class="row sub-para-w3layouts mt-5">

            <h3 class="shop-sing editContent" style="outline: none; cursor: inherit;">
                О фильме {{ movie.title }}
            </h3>
            <p>
                {% for image in movie.movieshots_set.all %}
                    <img src="{{ image.image.url }}" class="img-movie-shots m-1 " alt="{{ image.description }}">
                {% endfor %}
            </p>
            <p class="editContent" style="outline: none; cursor: inherit;">
                {{ movie.description|safe }}
            </p>
        </div>
        <hr>
        <div class="row">
            <div class="single-form-left">
                <!-- contact form grid -->
                <div class="contact-single">
                    <h3 class="editContent" style="outline: none; cursor: inherit;">
                        <span class="sub-tittle editContent">02</span>Оставить отзыв</h3>

                    <form action="{% url 'add_review' movie.id %}" method="post" class="mt-4" id="formReview">
                        {% csrf_token %}

                        <input type="hidden" name="parent" id="contactparent" value="">

                        <div class="form-group editContent">
                            <label for="contactcomment" class="editContent">
                                Ваш комментарий
                            </label>
                            <textarea class="form-control border" rows="5" id="contactcomment" required="" name="text"></textarea>
                        </div>
                        <div class="d-sm-flex">
                            <div class="col-sm-6 form-group p-0 editContent"
                                 style="outline: none; cursor: inherit;">
                                <label for="contactusername" class="editContent">
                                    Имя
                                </label>
                                <input type="text" class="form-control border" id="contactusername" required="" name="name">
                            </div>
                            <div class="col-sm-6 form-group ml-sm-3 editContent"
                                 style="outline: none; cursor: inherit;">
                                <label for="contactemail" class="editContent">
                                    Email
                                </label>
                                <input type="email" class="form-control border" id="contactemail" required="" name="email">
                            </div>
                        </div>
                        <button type="submit" class="mt-3 btn btn-success btn-block py-3">
                            Отправить
                        </button>
                    </form>

                </div>
                <!--  //contact form grid ends here -->
            </div>
            {% for review in movie.get_review %}
            <div class="media py-5 w-100">
                <img src="{% static 'images/te2.jpg' %}" class="mr-3 img-fluid" alt="image">
                <div class="media-body mt-4">
                    <h5 class="mt-0 editContent">{{ review.name }}</h5>
                    <p class="mt-2 editContent">{{ review.text }}</p>
                    <a href="#formReview" onclick="addReview('{{ review.name }}', '{{ review.id }}')">Ответить</a>
                    {% for rew in review.reviews_set.all%}
                        <div class="media mt-5 editContent">
                                <img src="{% static 'images/te2.jpg' %}" class="mr-4 img-fluid" alt="image">
                            <div class="media-body">
                                <h5 class="mt-0 editContent" style="outline: none; cursor: inherit;">
                                    {{ rew.name }}
                                </h5>
                                <p class="mt-2 editContent" style="outline: none; cursor: inherit;">
                                    {{ rew.text }}
                                </p>
                            </div>
                        </div>
                    {% endfor %}

                </div>
            </div>
            {% endfor %}
        </div>
    </div>

    <script src="{% static '/js/script.js' %}"></script>
    <script>
    function addReview(name, id) {
        document.getElementById("contactparent").value = id
        document.getElementById('contactcomment').innerText = `${name}, `
    }
    </script>
</div>
{% endblock movie %}

templates/movies/movie_list.html
{% extends 'movies/base.html' %}
{% block title %} {% endblock title %}
{% block header %} bg1 {% endblock header %}
{% block movie %}
    <div class="left-ads-display col-lg-9">
        <div class="row">
            {% for movie in movie_list %}
                <div class="col-md-4 product-men">
                    <div class="product-shoe-info editContent text-center mt-lg-4">
                        <div class="men-thumb-item">
                            <img src="{{ movie.poster.url }}" class="img-fluid mt-3" alt="" height="auto" width="320px">
                        </div>
                        <div class="item-info-product">
                            <h4 class="">
                                <a href="{{ movie.get_absolute_url }}"
                                   class="editContent">
                                    {{ movie.title }}
                                </a>
                            </h4>

                            <div class="product_price">
                                <div class="grid-price">
                                    <span class="money editContent">{{ movie.tagline }}</span>
                                </div>
                            </div>
                            <ul class="stars">
                                <li><a href="#"><span class="fa fa-star"
                                                      aria-hidden="true"></span></a>
                                </li>
                                <li><a href="#"><span class="fa fa-star"
                                                      aria-hidden="true"></span></a>
                                </li>
                                <li><a href="#"><span class="fa fa-star-half-o"
                                                      aria-hidden="true"></span></a>
                                </li>
                                <li><a href="#"><span class="fa fa-star-half-o"
                                                      aria-hidden="true"></span></a>
                                </li>
                                <li><a href="#"><span class="fa fa-star-o"
                                                      aria-hidden="true"></span></a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
        <!--<div class="grid-img-right mt-4 text-right bg bg1" >
            <span class="money editContent" >Flat 50% Off</span>
            <a href="moviesingle.html" class="btn" >Now</a>
        </div>-->
    </div>
{% endblock movie %}